Use of etcd, and loops

diff --git a/run-at-boot b/run-at-boot
--- a/run-at-boot
+++ b/run-at-boot
@@ -2,31 +2,58 @@
 export HERE=$(cd $(dirname "$0") ; pwd)
 export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/bin:$HERE
 export HOME=/root
+export ME=$(basename "$0")
 source /etc/airberry.conf
+function Log() {
+	echo "[$(date "+%Y/%m/%d %H:%M")] $*"
+}
+Log '** Starting **'
+Log 'Backlight off'
 $HERE/lcd.py backlight 0
+Log 'Displaying logo'
 $HERE/airberry_logo.py ; sleep 3
-IFACE=wlan0
+if ! /etc/init.d/etcd status >/dev/null 2>&1 
+then
+	echo 'Etcd is not running. Exiting.'
+	exit 1
+fi
+Log 'Creating dirs in etcd'
+curl -s -L http://127.0.0.1:4001/v2/keys/monitor -XPUT -d dir=true >/dev/null
+curl -s -L http://127.0.0.1:4001/v2/keys/cracked -XPUT -d dir=true >/dev/null
 if  ! ifconfig -a $IFACE >/dev/null 
 then
-	echo "$IFACE not found"
+	Log "$IFACE not found"
 	$HERE/lcd.py text 0 0 "No wireless,  nothing to    crack"
 	(sleep  10 ; [ -n "$(hostname -I)" ] && $HERE/lcd.py text 0 0 $(hostname -I)) &
 	exit 1
 fi
 echo $$ > /var/run/$(basename "$0").pid
-mkfifo /var/run/airberry
-nohup $HERE/check-fs-space.sh /tmp &
+Log 'Launching check-fs-space'
+nohup $HERE/check-fs-space.sh /tmp > /dev/null &
+Log 'Launching airberryd'
+nohup $HERE/airberryd > /tmp/airberryd.log &
 #airmon-ng start wlan0
 # Sort according to essid
 touch $HOME/cracked.csv
 sort -u -t ',' -k 3 $HOME/cracked.csv $HERE/cracked.csv > /tmp/c
 mv /tmp/c $HERE/cracked.csv
 rm -f $HOME/cracked.csv
+ifconfig ${IFACE}mon 2>/dev/null && airmon-ng stop ${IFACE}mon
 while true
 do
+	Log 'Looping...'
 	#$HERE/lcd.py cls
 	#$HERE/lcd.py text 0 2 'Wifite'
 	cd $HOME # As wifite save cracked.csv in the dir it was run from
-	$HOME/bin/wifite.py --wep -1 --all --scan-time 60 --power 15 --lcd >>/tmp/wifite.log
-	$HERE/broadcast-keys $DISPLAY >> /tmp/wifite.log
+	Log "Launching wifite"
+	$HOME/bin/wifite.py --wep -1 --all --scan-time 60 --power 15 --lcd >>/tmp/wifite.out
+	Log "Cleaning dirs left by airodump-ng "
+	ps -C airodump-ng -O cmd | grep tmp | awk '{print $12}' | while read d ; do [ -z "$d" ] && continue ;dir="$(dirname $d)"; Log "> $dir" ; rm -rf "$dir" ; done
+	for cmd in airodump-ng  aireplay-ng
+	do
+		Log "Killing stall $cmd"
+		pkill "$cmd"
+	done
+	Log "Launching broadcast-keys"
+	$HERE/broadcast-keys $DISPLAY >> /tmp/wifite.out
 done
